//=============================================================================
// Pixel shader input
//=============================================================================

struct PS_INPUT
{
    float4 Diffuse    : COLOR0;
    float4 Specular   : COLOR1;
    float2 TexCoords0 : TEXCOORD0;
    float2 TexCoords1 : TEXCOORD1;
};


//=============================================================================
// Lighting data
//=============================================================================

// EN: Ambient-light data matching the Engine-side constant-buffer layout.
//
// JP: Engine 側の Constant Buffer Layout と一致する
//     Ambient Light Data。
struct ShaderAmbientLightData
{
    float3 Color;
    float Padding;
};


// EN: Spotlight data matching the layout used by ModelPS.
//
// JP: ModelPS で使用している Layout と一致する
//     Spotlight Data。
struct ShaderSpotLightData
{
    float3 Position;
    float Range;

    float3 Direction;
    float Enabled;

    float3 Color;
    float Padding0;

    float InnerCos;
    float OuterCos;
    float Padding1;
    float Padding2;
};


// EN: Scene-lighting state supplied by the renderer.
//
// JP: Renderer から供給される Scene Lighting State。
cbuffer LightingBuffer : register(b4)
{
    ShaderAmbientLightData g_Ambient;
    ShaderSpotLightData g_SpotLight;
};


//=============================================================================
// Camera data
//=============================================================================

// EN: Must remain byte-compatible with the current 64-byte
//     Engine ShaderCameraData structure.
//
// JP: 現在の Engine 側 64 Byte ShaderCameraData と
//     Byte 単位で一致させる必要がある。
struct ShaderCameraData
{
    float3 Position;
    float TanHalfFovY;

    float3 Forward;
    float AspectRatio;

    float3 Right;
    float Padding0;

    float3 Up;
    float Padding1;
};


// EN: Camera state used by fullscreen ray reconstruction.
//
// JP: Fullscreen Ray Reconstruction で使用する Camera State。
cbuffer CameraBuffer : register(b6)
{
    ShaderCameraData g_Camera;
};


//=============================================================================
// Volumetric data
//=============================================================================

struct ShaderVolumetricData
{
    float Enabled;
    float Intensity;
    float Scattering;
    float Padding;
};


cbuffer VolumetricBuffer : register(b7)
{
    ShaderVolumetricData g_Volumetric;
};


//=============================================================================
// Scene depth / color
//=============================================================================

// EN: Linear view-depth texture generated by the scene-depth pass.
//
// JP: Scene Depth Pass で生成された Linear View Depth Texture。
Texture2D<float4> g_SceneDepth
    : register(t0);

SamplerState g_SceneDepthSampler
    : register(s0);


// EN: Scene color produced by the normal opaque scene pass.
//
// JP: 通常の Opaque Scene Pass で生成された Scene Color。
Texture2D<float4> g_SceneColor
    : register(t1);

SamplerState g_SceneColorSampler
    : register(s1);


//=============================================================================
// Main
//=============================================================================

float4 main(
    PS_INPUT input) : SV_TARGET0
{
    //-------------------------------------------------------------------------
    // UV -> NDC
    //-------------------------------------------------------------------------

    // EN: Convert fullscreen UV coordinates into centered NDC.
    //     Texture V increases downward, so Y is inverted.
    //
    // JP: Fullscreen UV を画面中心基準の NDC に変換する。
    //     Texture V は下方向へ増加するため Y を反転する。
    const float2 ndc =
        float2(
            input.TexCoords0.x * 2.0f - 1.0f,
            1.0f - input.TexCoords0.y * 2.0f);


    //-------------------------------------------------------------------------
    // Camera-space ray
    //-------------------------------------------------------------------------

    // EN: Reconstruct the normalized ray direction in camera-local space.
    //
    // JP: Camera Local Space 上の正規化された
    //     Ray Direction を再構築する。
    const float3 cameraRay =
        normalize(
            float3(
                ndc.x *
                    g_Camera.AspectRatio *
                    g_Camera.TanHalfFovY,

                ndc.y *
                    g_Camera.TanHalfFovY,

                1.0f));


    //-------------------------------------------------------------------------
    // World-space ray
    //-------------------------------------------------------------------------

    // EN: Transform the camera-local ray into world space using
    //     the camera orthonormal basis.
    //
    // JP: Camera の Orthonormal Basis を使用して
    //     Camera-Local Ray を World Space へ変換する。
    const float3 worldRay =
        normalize(
            g_Camera.Right *
                cameraRay.x +
            g_Camera.Up *
                cameraRay.y +
            g_Camera.Forward *
                cameraRay.z);


    //-------------------------------------------------------------------------
    // Scene depth
    //-------------------------------------------------------------------------

    // EN: Read linear depth measured along Camera Forward.
    //
    // JP: Camera Forward 方向に沿って計測された
    //     Linear Depth を読み取る。
    const float linearViewDepth =
        g_SceneDepth.Sample(
            g_SceneDepthSampler,
            input.TexCoords0).r;


    //-------------------------------------------------------------------------
    // Scene color
    //-------------------------------------------------------------------------

    // EN: Read the already-rendered scene color for final fullscreen
    //     volumetric composition.
    //
    // JP: 最終的な Fullscreen Volumetric Composition のために、
    //     既に描画された Scene Color を読み取る。
    const float4 sceneColor =
        g_SceneColor.Sample(
            g_SceneColorSampler,
            input.TexCoords0);


    //-------------------------------------------------------------------------
    // Scene ray distance
    //-------------------------------------------------------------------------

    // EN: Convert forward-axis view depth into the actual distance
    //     along this pixel's world-space ray.
    //
    // JP: Forward Axis 上の View Depth を、
    //     この Pixel の World-Space Ray 上の実距離へ変換する。
    const float rayForwardDot =
        dot(
            worldRay,
            normalize(
                g_Camera.Forward));

    const float safeRayForwardDot =
        max(
            rayForwardDot,
            0.0001f);

    const float sceneRayDistance =
        linearViewDepth /
        safeRayForwardDot;


    //-------------------------------------------------------------------------
    // Spotlight cone
    //-------------------------------------------------------------------------

    // EN: Spotlight Direction defines the cone axis from the apex
    //     toward the beam end.
    //
    // JP: Spotlight Direction は Cone Apex から Beam End へ向かう
    //     Cone Axis を表す。
    const float3 coneDirection =
        normalize(
            g_SpotLight.Direction);


    // EN: Measure how closely this pixel ray follows
    //     the spotlight forward axis.
    //
    // JP: この Pixel Ray が Spotlight Forward Axis と
    //     どれだけ一致しているかを求める。
    const float rayConeCos =
        dot(
            worldRay,
            coneDirection);


    //-------------------------------------------------------------------------
    // Spotlight angular feather
    //-------------------------------------------------------------------------

    // EN: Width of the smooth transition between the outer cone
    //     and fully illuminated inner cone.
    //
    // JP: Outer Cone と完全に明るい Inner Cone の間にある
    //     Smooth Transition の幅。
    const float coneFeatherRange =
        max(
            g_SpotLight.InnerCos -
                g_SpotLight.OuterCos,
            0.0001f);


    //-------------------------------------------------------------------------
    // Finite cone membership
    //-------------------------------------------------------------------------

    const bool spotlightEnabled =
        g_SpotLight.Enabled >
        0.5f;

    const bool rayInsideCone =
        rayConeCos >=
        g_SpotLight.OuterCos;

    const bool rayMovesForward =
        rayConeCos >
        0.0001f;


    // EN: Pixels outside the active forward flashlight cone
    //     contain no valid volumetric segment.
    //
    // JP: 有効な Forward Flashlight Cone の外側にある Pixel には
    //     Volumetric Segment は存在しない。
    if (!spotlightEnabled ||
        !rayInsideCone ||
        !rayMovesForward)
    {
        return sceneColor;
    }


    //-------------------------------------------------------------------------
    // Finite cone end-plane distance
    //-------------------------------------------------------------------------

    // EN: Measure the camera-ray origin relative to the spotlight apex.
    //
    // JP: Spotlight Apex を基準として Camera Ray Origin の位置を求める。
    const float3 apexToRayOrigin =
        g_Camera.Position -
        g_SpotLight.Position;


    // EN: Axial position of the current ray origin relative to
    //     the spotlight apex.
    //
    // JP: Spotlight Apex を基準とした
    //     Ray Origin の Axis 方向位置。
    const float originAxialDistance =
        dot(
            apexToRayOrigin,
            coneDirection);


    // EN: Remaining axial distance to the finite cone end plane.
    //
    // JP: Finite Cone の End Plane まで残っている
    //     Axis 方向距離。
    const float remainingAxialDistance =
        g_SpotLight.Range -
        originAxialDistance;


    const bool endPlaneIsAhead =
        remainingAxialDistance >
        0.0f;


    // EN: Stop when the finite cone end plane lies behind
    //     the current ray origin.
    //
    // JP: Finite Cone の End Plane が現在の Ray Origin より
    //     後方にある場合は Volumetric Segment を生成しない。
    if (!endPlaneIsAhead)
    {
        return sceneColor;
    }


    // EN: Distance along this pixel ray until it reaches
    //     the finite flashlight cone end plane.
    //
    // JP: この Pixel Ray が Finite Flashlight Cone の
    //     End Plane に到達するまでの Ray 上の距離。
    const float coneExitDistance =
        remainingAxialDistance /
        rayConeCos;


    //-------------------------------------------------------------------------
    // Scene-depth clamp
    //-------------------------------------------------------------------------

    // EN: Zero linear depth is the sentinel used when no opaque
    //     scene surface was rendered at this pixel.
    //
    // JP: Linear Depth = 0 は、この Pixel に Opaque Scene Surface が
    //     描画されなかったことを表す Sentinel。
    const bool hasSceneSurface =
        linearViewDepth >
        0.0001f;


    // EN: Terminate the ray at whichever comes first:
    //     scene geometry or the flashlight cone end.
    //
    // JP: Scene Geometry と Flashlight Cone End のうち
    //     手前側で Ray を終了する。
    const float raySegmentEnd =
        hasSceneSurface
        ? min(
            coneExitDistance,
            sceneRayDistance)
        : coneExitDistance;


    //-------------------------------------------------------------------------
    // Raymarch interval
    //-------------------------------------------------------------------------

    const float segmentLength =
        max(
            raySegmentEnd,
            0.0f);


    if (g_Volumetric.Enabled <= 0.5f ||
        segmentLength <= 0.0001f)
    {
        return sceneColor;
    }


    //-------------------------------------------------------------------------
    // Medium properties
    //-------------------------------------------------------------------------

    // EN: Homogeneous-medium scattering coefficient.
    //
    //     Spotlight angle and distance must not be mixed into this value,
    //     because they describe the light source rather than the medium.
    //
    // JP: 均一 Medium の Scattering Coefficient。
    //
    //     Spotlight の Angle や Distance は Medium ではなく
    //     Light Source の性質なので、この値には混ぜない。
    const float mediumScattering =
        max(
            g_Volumetric.Scattering,
            0.0f);


    // EN: V1 uses the same coefficient for extinction and scattering.
    //     Absorption can be separated later.
    //
    // JP: V1 では Extinction と Scattering に同じ係数を使用する。
    //     Absorption は後で分離できる。
    const float mediumExtinction =
        mediumScattering;


    //-------------------------------------------------------------------------
    // Raymarch setup
    //-------------------------------------------------------------------------

    // EN: Fixed low sample count for the first physically separated
    //     single-scattering implementation.
    //
    // JP: Light と Medium を分離した最初の Single-Scattering 実装では、
    //     固定の少数 Sample を使用する。
    const int SampleCount =
        8;


    const float stepLength =
        segmentLength /
        SampleCount;


    // EN: Volumetric radiance accumulated along the camera ray.
    //
    // JP: Camera Ray に沿って積算される Volumetric Radiance。
    float accumulatedScattering =
        0.0f;


    // EN: Transmittance remaining from the current sample toward
    //     the camera along the view path.
    //
    // JP: View Path 上で Current Sample から Camera までに残る
    //     Transmittance。
    float transmittance =
        1.0f;


    //-------------------------------------------------------------------------
    // Raymarch
    //-------------------------------------------------------------------------

    // EN: March from the camera toward the clamped ray end and evaluate
    //     one representative sample at the midpoint of each step.
    //
    // JP: Camera から Clamp 済み Ray End まで March し、
    //     各 Step の中点で代表 Sample を評価する。
    [unroll]
    for (int sampleIndex = 0;
        sampleIndex < SampleCount;
        ++sampleIndex)
    {
        const float sampleDistance =
            stepLength *
            (sampleIndex + 0.5f);


        const float3 samplePosition =
            g_Camera.Position +
            worldRay *
            sampleDistance;


        // ---------------------------------------------------------------------
        // Spotlight relation at this sample
        // ---------------------------------------------------------------------

        // EN: Vector from the spotlight origin to the sample.
        //
        // JP: Spotlight Origin から Sample へのベクトル。
        const float3 lightToSample =
            samplePosition -
            g_SpotLight.Position;


        const float sampleLightDistance =
            length(
                lightToSample);


        // EN: Ignore the numerical singularity directly at the light origin.
        //
        // JP: Light Origin 直上で発生する数値的特異点を無視する。
        if (sampleLightDistance <= 0.0001f)
        {
            continue;
        }


        const float3 sampleLightDirection =
            lightToSample /
            sampleLightDistance;


        //-------------------------------------------------------------------------
        // Per-sample cone attenuation
        //-------------------------------------------------------------------------

        const float sampleConeCos =
            dot(
                sampleLightDirection,
                coneDirection);


        if (sampleConeCos <
            g_SpotLight.OuterCos)
        {
            continue;
        }


        // EN: Smoothly fade from OuterCos to InnerCos.
        //
        // JP: OuterCos から InnerCos まで滑らかに減衰する。
        const float sampleConeFactor =
            saturate(
                (sampleConeCos -
                    g_SpotLight.OuterCos) /
                coneFeatherRange);


        //-------------------------------------------------------------------------
        // Spotlight range attenuation
        //-------------------------------------------------------------------------

        // EN: Normalize the distance from spotlight to sample over
        //     the finite flashlight range.
        //
        // JP: Spotlight から Sample までの距離を
        //    有限 Flashlight Range で正規化する。
        const float normalizedBeamDistance =
            saturate(
                sampleLightDistance /
                max(
                    g_SpotLight.Range,
                    0.0001f));


        // EN: V1 geometric range fade.
        //
        //     This is still not a physical inverse-square falloff.
        //     It only provides a smooth finite-range attenuation.
        //
        // JP: V1 の Geometric Range Fade。
        //
        //     まだ物理的な Inverse-Square Falloff ではなく、
        //     有限 Range を滑らかに減衰させるための係数。
        float beamDistanceFactor =
            1.0f -
            normalizedBeamDistance;


        beamDistanceFactor *=
            beamDistanceFactor;


        //-------------------------------------------------------------------------
        // Light-path transmittance
        //-------------------------------------------------------------------------

        // EN: Light traveling from the spotlight to this sample is attenuated
        //     by the participating medium.
        //
        //     This is separate from spotlight angular/range attenuation.
        //
        // JP: Spotlight から Sample まで進む光は Participating Medium
        //     による Extinction を受ける。
        //
        //     Spotlight の Angle / Range Attenuation とは別に扱う。
        const float lightTransmittance =
            exp(
                -mediumExtinction *
                sampleLightDistance);


        // EN: Amount of spotlight radiance reaching this sample.
        //
        // JP: 現在の Sample に到達する Spotlight Radiance の割合。
        const float sampleLightFactor =
            sampleConeFactor *
            beamDistanceFactor *
            lightTransmittance;


        //-------------------------------------------------------------------------
        // Scattering inside this step
        //-------------------------------------------------------------------------

        // EN: Transmittance across one marching step caused purely by
        //     the homogeneous medium.
        //
        // JP: 均一 Medium によって 1 Marching Step 内で発生する
        //     Transmittance。
        const float stepTransmittance =
            exp(
                -mediumExtinction *
                stepLength);


        // EN: Since V1 assumes scattering == extinction, the scattered
        //     fraction in this step is 1 - stepTransmittance.
        //
        // JP: V1 では Scattering == Extinction と仮定しているため、
        //     この Step 内で散乱する割合は
        //     1 - stepTransmittance となる。
        const float stepScattering =
            1.0f -
            stepTransmittance;


        // EN: Approximate single-scattering contribution:
        //
        //       view-path transmittance
        //     × spotlight radiance reaching the sample
        //     × scattering occurring in this step
        //
        // JP: Single-Scattering Contribution の近似：
        //
        //       View Path Transmittance
        //     × Sample に到達する Spotlight Radiance
        //     × この Step 内で発生する Scattering
        const float stepContribution =
            transmittance *
            sampleLightFactor *
            stepScattering;


        accumulatedScattering +=
            stepContribution;


        // EN: Update remaining view-path transmittance for the next sample.
        //
        // JP: 次の Sample に向けて残りの
        //     View Path Transmittance を更新する。
        transmittance *=
            stepTransmittance;
    }


    //-------------------------------------------------------------------------
    // Final volumetric intensity
    //-------------------------------------------------------------------------

    // EN: Apply user-controlled global intensity after physically separated
    //     light/medium accumulation.
    //
    // JP: Light と Medium を分離した積算後に、
    //     User 制御の Global Intensity を適用する。
    const float volumetricIntensity =
        saturate(
            accumulatedScattering *
            max(
                g_Volumetric.Intensity,
                0.0f));


    //-------------------------------------------------------------------------
    // Final composition
    //-------------------------------------------------------------------------

    // EN: Convert scalar volumetric intensity into spotlight color.
    //
    // JP: Scalar Volumetric Intensity を
    //     Spotlight Color に変換する。
    const float3 volumetricColor =
        g_SpotLight.Color *
        volumetricIntensity;


    // EN: Compose the volumetric contribution over the existing
    //     scene color.
    //
    //     The renderer is still using an LDR composition path,
    //     therefore the result is clamped to [0, 1].
    //
    // JP: 既存の Scene Color に Volumetric Contribution を加算する。
    //
    //     現在は LDR Composition Path のため、
    //     結果を [0, 1] に Clamp する。
    const float3 finalColor =
        saturate(
            sceneColor.rgb +
            volumetricColor);


    return float4(
        finalColor,
        sceneColor.a);
}