struct VS_INPUT
{
    float3 Position    : POSITION0;
    float3 Normal      : NORMAL0;

    float4 Diffuse     : COLOR0;
    float4 Specular    : COLOR1;

    float2 TexCoords0  : TEXCOORD0;
    float2 TexCoords1  : TEXCOORD1;
};

struct VS_OUTPUT
{
    float4 Diffuse       : COLOR0;
    float3 WorldPosition : TEXCOORD0;
    float4 Position      : SV_POSITION;
};


// EN: DxLib-provided D3D11 vertex-shader constants.
//     The cone vertices are already expressed in world space,
//     so only View and Projection are used here.
//
// JP: DxLib が提供する D3D11 Vertex Shader Constant。
//     Cone Vertex は既に World Space で生成されているため、
//     ここでは View と Projection のみを使用する。
struct DX_D3D11_VS_CONST_BUFFER_BASE
{
    float4 AntiViewportMatrix[4];
    float4 ProjectionMatrix[4];
    float4 ViewMatrix[3];
    float4 LocalWorldMatrix[3];

    float4 ToonOutLineSize;

    float DiffuseSource;
    float SpecularSource;
    float MulSpecularColor;
    float Padding;
};

cbuffer DxLibVertexBase : register(b1)
{
    DX_D3D11_VS_CONST_BUFFER_BASE g_Base;
};


VS_OUTPUT main(VS_INPUT input)
{
    VS_OUTPUT output;

    // EN: Input positions are already world-space positions
    //     generated by DxRenderer's volumetric cone geometry.
    //
    // JP: Input Position は DxRenderer が生成した
    //     World Space 上の Volumetric Cone Vertex。
    const float4 worldPosition =
        float4(
            input.Position,
            1.0f);

    // EN: Pass the world-space position to the pixel shader so
    //     volumetric attenuation can be evaluated per pixel.
    //
    // JP: Pixel Shader 側で Volumetric Attenuation を計算できるよう、
    //     World Space Position を渡す。
    output.WorldPosition =
        worldPosition.xyz;

    float4 viewPosition;

    viewPosition.x =
        dot(
            worldPosition,
            g_Base.ViewMatrix[0]);

    viewPosition.y =
        dot(
            worldPosition,
            g_Base.ViewMatrix[1]);

    viewPosition.z =
        dot(
            worldPosition,
            g_Base.ViewMatrix[2]);

    viewPosition.w = 1.0f;


    output.Position.x =
        dot(
            viewPosition,
            g_Base.ProjectionMatrix[0]);

    output.Position.y =
        dot(
            viewPosition,
            g_Base.ProjectionMatrix[1]);

    output.Position.z =
        dot(
            viewPosition,
            g_Base.ProjectionMatrix[2]);

    output.Position.w =
        dot(
            viewPosition,
            g_Base.ProjectionMatrix[3]);


    output.Diffuse =
        input.Diffuse;

    return output;
}