//=============================================================================
// Pixel shader input
//=============================================================================

struct PS_INPUT
{
    float4 Diffuse    : COLOR0;
    float4 Specular   : COLOR1;
    float2 TexCoords0 : TEXCOORD0;
    float2 TexCoords1 : TEXCOORD1;
};


//=============================================================================
// Lighting data
//=============================================================================

// EN: Ambient-light data matching the Engine-side constant-buffer layout.
//
// JP: Engine 側の Constant Buffer Layout と一致する
//     Ambient Light Data。
struct ShaderAmbientLightData
{
    float3 Color;
    float Padding;
};


// EN: Spotlight data matching the layout used by ModelPS.
//
// JP: ModelPS で使用している Layout と一致する
//     Spotlight Data。
struct ShaderSpotLightData
{
    float3 Position;
    float Range;

    float3 Direction;
    float Enabled;

    float3 Color;
    float Padding0;

    float InnerCos;
    float OuterCos;
    float Padding1;
    float Padding2;
};


// EN: Scene-lighting state supplied by the renderer.
//
// JP: Renderer から供給される Scene Lighting State。
cbuffer LightingBuffer : register(b4)
{
    ShaderAmbientLightData g_Ambient;
    ShaderSpotLightData g_SpotLight;
};


//=============================================================================
// Camera data
//=============================================================================

// EN: Must remain byte-compatible with the current 64-byte
//     Engine ShaderCameraData structure.
//
// JP: 現在の Engine 側 64 Byte ShaderCameraData と
//     Byte 単位で一致させる必要がある。
struct ShaderCameraData
{
    float3 Position;
    float TanHalfFovY;

    float3 Forward;
    float AspectRatio;

    float3 Right;
    float Padding0;

    float3 Up;
    float Padding1;
};


// EN: Camera state used by fullscreen ray reconstruction.
//
// JP: Fullscreen Ray Reconstruction で使用する Camera State。
cbuffer CameraBuffer : register(b6)
{
    ShaderCameraData g_Camera;
};


//=============================================================================
// Volumetric data
//=============================================================================

struct ShaderVolumetricData
{
    float Enabled;
    float Intensity;
    float Scattering;
    float Padding;
};


cbuffer VolumetricBuffer : register(b7)
{
    ShaderVolumetricData g_Volumetric;
};


//=============================================================================
// Scene depth / color
//=============================================================================

// EN: Linear view-depth texture generated by the scene-depth pass.
//
// JP: Scene Depth Pass で生成された Linear View Depth Texture。
Texture2D<float4> g_SceneDepth
    : register(t0);

SamplerState g_SceneDepthSampler
    : register(s0);


// EN: Scene color produced by the normal opaque scene pass.
//
// JP: 通常の Opaque Scene Pass で生成された Scene Color。
Texture2D<float4> g_SceneColor
    : register(t1);

SamplerState g_SceneColorSampler
    : register(s1);


//=============================================================================
// Main
//=============================================================================

float4 main(
    PS_INPUT input) : SV_TARGET0
{
    //-------------------------------------------------------------------------
    // UV -> NDC
    //-------------------------------------------------------------------------

    // EN: Convert fullscreen UV coordinates into centered NDC.
    //     Texture V increases downward, so Y is inverted.
    //
    // JP: Fullscreen UV を画面中心基準の NDC に変換する。
    //     Texture V は下方向へ増加するため Y を反転する。
    const float2 ndc =
        float2(
            input.TexCoords0.x * 2.0f - 1.0f,
            1.0f - input.TexCoords0.y * 2.0f);


    //-------------------------------------------------------------------------
    // Camera-space ray
    //-------------------------------------------------------------------------

    // EN: Reconstruct the normalized ray direction in camera-local space.
    //
    // JP: Camera Local Space 上の正規化された
    //     Ray Direction を再構築する。
    const float3 cameraRay =
        normalize(
            float3(
                ndc.x *
                    g_Camera.AspectRatio *
                    g_Camera.TanHalfFovY,

                ndc.y *
                    g_Camera.TanHalfFovY,

                1.0f));


    //-------------------------------------------------------------------------
    // World-space ray
    //-------------------------------------------------------------------------

    // EN: Transform the camera-local ray into world space using
    //     the camera orthonormal basis.
    //
    // JP: Camera の Orthonormal Basis を使用して
    //     Camera-Local Ray を World Space へ変換する。
    const float3 worldRay =
        normalize(
            g_Camera.Right *
                cameraRay.x +
            g_Camera.Up *
                cameraRay.y +
            g_Camera.Forward *
                cameraRay.z);


    //-------------------------------------------------------------------------
    // Scene depth
    //-------------------------------------------------------------------------

    // EN: Read linear depth measured along Camera Forward.
    //
    // JP: Camera Forward 方向に沿って計測された
    //     Linear Depth を読み取る。
    const float linearViewDepth =
        g_SceneDepth.Sample(
            g_SceneDepthSampler,
            input.TexCoords0).r;


    //-------------------------------------------------------------------------
    // Scene color
    //-------------------------------------------------------------------------

    // EN: Read the already-rendered scene color for final fullscreen
    //     volumetric composition.
    //
    // JP: 最終的な Fullscreen Volumetric Composition のために、
    //     既に描画された Scene Color を読み取る。
    const float4 sceneColor =
        g_SceneColor.Sample(
            g_SceneColorSampler,
            input.TexCoords0);


    //-------------------------------------------------------------------------
    // Scene ray distance
    //-------------------------------------------------------------------------

    // EN: Convert forward-axis view depth into the actual distance
    //     along this pixel's world-space ray.
    //
    // JP: Forward Axis 上の View Depth を、
    //     この Pixel の World-Space Ray 上の実距離へ変換する。
    const float rayForwardDot =
        dot(
            worldRay,
            normalize(
                g_Camera.Forward));

    const float safeRayForwardDot =
        max(
            rayForwardDot,
            0.0001f);

    const float sceneRayDistance =
        linearViewDepth /
        safeRayForwardDot;


    //-------------------------------------------------------------------------
    // Spotlight cone
    //-------------------------------------------------------------------------

    // EN: Spotlight Direction defines the cone axis from the apex
    //     toward the beam end.
    //
    // JP: Spotlight Direction は Cone Apex から Beam End へ向かう
    //     Cone Axis を表す。
    const float3 coneDirection =
        normalize(
            g_SpotLight.Direction);


    //-------------------------------------------------------------------------
    // Spotlight angular feather
    //-------------------------------------------------------------------------

    // EN: Width of the smooth transition between the outer cone
    //     and fully illuminated inner cone.
    //
    // JP: Outer Cone と完全に明るい Inner Cone の間にある
    //     Smooth Transition の幅。
    const float coneFeatherRange =
        max(
            g_SpotLight.InnerCos -
                g_SpotLight.OuterCos,
            0.0001f);


    //-------------------------------------------------------------------------
    // Spotlight enabled state
    //-------------------------------------------------------------------------

    const bool spotlightEnabled =
        g_SpotLight.Enabled >
        0.5f;

    // EN: With separate camera and light origins, a camera ray can enter
    //     the light cone later. Test cone membership at each march sample.
    // JP: Camera と Light の Origin が異なると、Camera Ray は途中で
    //     Light Cone に入るため、Cone 判定は各 March Sample で行う。
    if (!spotlightEnabled)
    {
        return sceneColor;
    }


    //-------------------------------------------------------------------------
    // Spotlight range boundary
    //-------------------------------------------------------------------------

    // EN: SpotLight Range is defined as the maximum Euclidean distance
    //     from the light origin. The volumetric ray therefore terminates
    //     at the far intersection with this range sphere.
    //
    // JP: SpotLight Range は Light Origin からの最大 Euclidean Distance
    //     として定義する。そのため Volumetric Ray は、この Range Sphere
    //     との Far Intersection で終了する。
    const float safeLightRange =
        max(
            g_SpotLight.Range,
            0.0001f);

    const float rangeSquared =
        safeLightRange *
        safeLightRange;


    // EN: Vector from the spotlight origin to the camera-ray origin.
    //
    // JP: SpotLight Origin から Camera Ray Origin へのベクトル。
    const float3 lightToRayOrigin =
        g_Camera.Position -
        g_SpotLight.Position;

    const float rayOriginDistanceSquared =
        dot(
            lightToRayOrigin,
            lightToRayOrigin);


    // EN: The current flashlight implementation expects the camera to
    //     remain inside the spotlight's effective range.
    //
    // JP: 現在の Flashlight 実装では Camera が SpotLight の
    //     有効 Range 内に存在することを前提とする。
    if (rayOriginDistanceSquared >=
        rangeSquared)
    {
        return sceneColor;
    }


    // EN: Solve the ray/sphere intersection for a normalized ray:
    //
    //     |O + tD|^2 = R^2
    //
    //     We need the far positive intersection because marching starts
    //     at the camera and continues until the light range ends.
    //
    // JP: Normalized Ray に対する Ray / Sphere Intersection
    //
    //     |O + tD|^2 = R^2
    //
    //     を解く。Marching は Camera から開始するため、
    //     Light Range 終端となる Far Positive Intersection を使用する。
    const float rayOriginAlongRay =
        dot(
            lightToRayOrigin,
            worldRay);

    const float rangeDiscriminant =
        rayOriginAlongRay *
            rayOriginAlongRay -
        (
            rayOriginDistanceSquared -
            rangeSquared
        );

    if (rangeDiscriminant <=
        0.0f)
    {
        return sceneColor;
    }

    const float rangeExitDistance =
        -rayOriginAlongRay +
        sqrt(
            max(
                rangeDiscriminant,
                0.0f));

    if (rangeExitDistance <=
        0.0001f)
    {
        return sceneColor;
    }

    //-------------------------------------------------------------------------
    // Scene-depth clamp
    //-------------------------------------------------------------------------

    // EN: Zero linear depth is the sentinel used when no opaque
    //     scene surface was rendered at this pixel.
    //
    // JP: Linear Depth = 0 は、この Pixel に Opaque Scene Surface が
    //     描画されなかったことを表す Sentinel。
    const bool hasSceneSurface =
        linearViewDepth >
        0.0001f;


    // EN: Terminate the ray at whichever comes first:
    //     scene geometry or the spotlight range boundary.
    //
    // JP: Scene Geometry と SpotLight Range Boundary のうち
    //     手前側で Ray を終了する。
    const float raySegmentEnd =
        hasSceneSurface
        ? min(
            rangeExitDistance,
            sceneRayDistance)
        : rangeExitDistance;


    //-------------------------------------------------------------------------
    // Raymarch interval
    //-------------------------------------------------------------------------

    const float segmentLength =
        max(
            raySegmentEnd,
            0.0f);


    if (g_Volumetric.Enabled <= 0.5f ||
        segmentLength <= 0.0001f)
    {
        return sceneColor;
    }


    //-------------------------------------------------------------------------
    // Medium properties
    //-------------------------------------------------------------------------

    // EN: Homogeneous-medium scattering coefficient.
    //
    //     Spotlight angle and distance must not be mixed into this value,
    //     because they describe the light source rather than the medium.
    //
    // JP: 均一 Medium の Scattering Coefficient。
    //
    //     Spotlight の Angle や Distance は Medium ではなく
    //     Light Source の性質なので、この値には混ぜない。
    const float mediumScattering =
        max(
            g_Volumetric.Scattering,
            0.0f);


    // EN: V1 uses the same coefficient for extinction and scattering.
    //     Absorption can be separated later.
    //
    // JP: V1 では Extinction と Scattering に同じ係数を使用する。
    //     Absorption は後で分離できる。
    const float mediumExtinction =
        mediumScattering;


    //-------------------------------------------------------------------------
    // Raymarch setup
    //-------------------------------------------------------------------------

    // EN: Intermediate sample count for comparing banding and GPU cost
    //     after the raymarch math and attenuation are stable.
    //
    // JP: Raymarch 数学と Attenuation の確認後、Banding と GPU Cost を
    //     比較するための中間 Sample Count。
    const int SampleCount =
        16;


    const float stepLength =
        segmentLength /
        SampleCount;


    // EN: Volumetric radiance accumulated along the camera ray.
    //
    // JP: Camera Ray に沿って積算される Volumetric Radiance。
    float accumulatedScattering =
        0.0f;


    // EN: Transmittance remaining from the current sample toward
    //     the camera along the view path.
    //
    // JP: View Path 上で Current Sample から Camera までに残る
    //     Transmittance。
    float transmittance =
        1.0f;


    //-------------------------------------------------------------------------
    // Raymarch
    //-------------------------------------------------------------------------

    // EN: March from the camera toward the clamped ray end and evaluate
    //     one representative sample at the midpoint of each step.
    //
    // JP: Camera から Clamp 済み Ray End まで March し、
    //     各 Step の中点で代表 Sample を評価する。
    [unroll]
    for (int sampleIndex = 0;
        sampleIndex < SampleCount;
        ++sampleIndex)
    {
        const float sampleDistance =
            stepLength *
            (sampleIndex + 0.5f);


        const float3 samplePosition =
            g_Camera.Position +
            worldRay *
            sampleDistance;


        // ---------------------------------------------------------------------
        // Spotlight relation at this sample
        // ---------------------------------------------------------------------

        // EN: Vector from the spotlight origin to the sample.
        //
        // JP: Spotlight Origin から Sample へのベクトル。
        const float3 lightToSample =
            samplePosition -
            g_SpotLight.Position;


        const float sampleLightDistance =
            length(
                lightToSample);


        // EN: Ignore the numerical singularity directly at the light origin.
        //
        // JP: Light Origin 直上で発生する数値的特異点を無視する。
        if (sampleLightDistance <= 0.0001f)
        {
            continue;
        }


        const float3 sampleLightDirection =
            lightToSample /
            sampleLightDistance;


        //-------------------------------------------------------------------------
        // Per-sample cone attenuation
        //-------------------------------------------------------------------------

        const float sampleConeCos =
            dot(
                sampleLightDirection,
                coneDirection);


        if (sampleConeCos <
            g_SpotLight.OuterCos)
        {
            continue;
        }


        // EN: Smoothly fade from OuterCos to InnerCos.
        //
        // JP: OuterCos から InnerCos まで滑らかに減衰する。
        const float sampleConeFactor =
            saturate(
                (sampleConeCos -
                    g_SpotLight.OuterCos) /
                coneFeatherRange);


        // EN: Apply a weak forward-biased Henyey-Greenstein phase response.
        //     The cosine compares incoming light travel with scattered travel
        //     toward the camera; normalization preserves isotropic average energy.
        //
        // JP: 弱い Forward-Biased Henyey-Greenstein Phase Response を適用する。
        //     Light の入射方向と Camera への散乱方向を比較し、
        //     Isotropic Average Energy を保つ比率で計算する。
        const float phaseAnisotropy =
            0.2f;

        const float phaseCosine =
            dot(
                sampleLightDirection,
                -worldRay);

        const float phaseDenominator =
            max(
                1.0f +
                    phaseAnisotropy *
                    phaseAnisotropy -
                    2.0f *
                    phaseAnisotropy *
                    phaseCosine,
                0.0001f);

        const float phaseFunctionFactor =
            (1.0f -
                phaseAnisotropy *
                phaseAnisotropy) /
            pow(
                phaseDenominator,
                1.5f);


        //-------------------------------------------------------------------------
        // Spotlight distance attenuation
        //-------------------------------------------------------------------------

        const float normalizedLightDistance =
            saturate(
                sampleLightDistance /
                safeLightRange);


        // EN: Soften inverse-square falloff near the source while retaining
        //     inverse-square behavior at distances well beyond the softening radius.
        //
        // JP: 光源近傍の Inverse-Square Falloff を Softening しつつ、
        //     Radius より十分遠方では Inverse-Square の挙動を保つ。
        const float attenuationSofteningDistance =
            0.5f;

        const float softeningDistanceSquared =
            attenuationSofteningDistance *
            attenuationSofteningDistance;

        const float distanceSquared =
            sampleLightDistance *
            sampleLightDistance;

        const float inverseSquareFactor =
            softeningDistanceSquared /
            (distanceSquared +
                softeningDistanceSquared);


        // EN: Smoothly fade the light to zero as the sample approaches Range.
        //
        // JP: Sample が Range に近づくにつれて Light を滑らかに 0 へ減衰する。
        float rangeCutoff =
            1.0f -
            normalizedLightDistance;

        rangeCutoff *=
            rangeCutoff;


        // EN: Keep geometric attenuation separate from cone and medium terms.
        //
        // JP: 幾何学的 Attenuation を Cone / Medium 項から分離して保つ。
        const float beamDistanceFactor =
            inverseSquareFactor *
            rangeCutoff;


        //-------------------------------------------------------------------------
        // Light-path transmittance
        //-------------------------------------------------------------------------

        // EN: Light traveling from the spotlight to this sample is attenuated
        //     by the participating medium.
        //
        //     This is separate from spotlight angular/range attenuation.
        //
        // JP: Spotlight から Sample まで進む光は Participating Medium
        //     による Extinction を受ける。
        //
        //     Spotlight の Angle / Range Attenuation とは別に扱う。
        const float lightTransmittance =
            exp(
                -mediumExtinction *
                sampleLightDistance);


        // EN: Amount of spotlight radiance reaching this sample.
        //
        // JP: 現在の Sample に到達する Spotlight Radiance の割合。
        const float sampleLightFactor =
            sampleConeFactor *
            beamDistanceFactor *
            phaseFunctionFactor *
            lightTransmittance;


        //-------------------------------------------------------------------------
        // Scattering inside this step
        //-------------------------------------------------------------------------

        // EN: Transmittance across one marching step caused purely by
        //     the homogeneous medium.
        //
        // JP: 均一 Medium によって 1 Marching Step 内で発生する
        //     Transmittance。
        const float stepTransmittance =
            exp(
                -mediumExtinction *
                stepLength);


        // EN: Since V1 assumes scattering == extinction, the scattered
        //     fraction in this step is 1 - stepTransmittance.
        //
        // JP: V1 では Scattering == Extinction と仮定しているため、
        //     この Step 内で散乱する割合は
        //     1 - stepTransmittance となる。
        const float stepScattering =
            1.0f -
            stepTransmittance;


        // EN: Approximate single-scattering contribution:
        //
        //       view-path transmittance
        //     × spotlight radiance reaching the sample
        //     × scattering occurring in this step
        //
        // JP: Single-Scattering Contribution の近似：
        //
        //       View Path Transmittance
        //     × Sample に到達する Spotlight Radiance
        //     × この Step 内で発生する Scattering
        const float stepContribution =
            transmittance *
            sampleLightFactor *
            stepScattering;


        accumulatedScattering +=
            stepContribution;


        // EN: Update remaining view-path transmittance for the next sample.
        //
        // JP: 次の Sample に向けて残りの
        //     View Path Transmittance を更新する。
        transmittance *=
            stepTransmittance;
    }


    //-------------------------------------------------------------------------
    // Final volumetric intensity
    //-------------------------------------------------------------------------

    // EN: Apply user-controlled global intensity after physically separated
    //     light/medium accumulation.
    //
    // JP: Light と Medium を分離した積算後に、
    //     User 制御の Global Intensity を適用する。
    const float volumetricIntensity =
        saturate(
            accumulatedScattering *
            max(
                g_Volumetric.Intensity,
                0.0f));


    //-------------------------------------------------------------------------
    // Final composition
    //-------------------------------------------------------------------------

    // EN: Convert scalar volumetric intensity into spotlight color.
    //
    // JP: Scalar Volumetric Intensity を
    //     Spotlight Color に変換する。
    const float3 volumetricColor =
        g_SpotLight.Color *
        volumetricIntensity;


    // EN: Compose the volumetric contribution over the existing
    //     scene color.
    //
    //     The renderer is still using an LDR composition path,
    //     therefore the result is clamped to [0, 1].
    //
    // JP: 既存の Scene Color に Volumetric Contribution を加算する。
    //
    //     現在は LDR Composition Path のため、
    //     結果を [0, 1] に Clamp する。
    const float3 finalColor =
        saturate(
            sceneColor.rgb +
            volumetricColor);


    return float4(
        finalColor,
        sceneColor.a);
}
